/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedBlitzRouteImport } from './routes/_authenticated/blitz'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedMistakesRouteImport } from './routes/_authenticated/mistakes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedStoryRouteImport } from './routes/_authenticated/story'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedBattleCodeRouteImport } from './routes/_authenticated/battle.$code'
import { Route as AuthenticatedLearnCodeRouteImport } from './routes/_authenticated/learn.$code'
import { Route as AuthenticatedSubjectCodeRouteImport } from './routes/_authenticated/subject.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlitzRoute = AuthenticatedBlitzRouteImport.update({
  id: '/blitz',
  path: '/blitz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMistakesRoute = AuthenticatedMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryRoute = AuthenticatedStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleCodeRoute = AuthenticatedBattleCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AuthenticatedBattleRoute,
} as any)
const AuthenticatedLearnCodeRoute = AuthenticatedLearnCodeRouteImport.update({
  id: '/learn/$code',
  path: '/learn/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectCodeRoute =
  AuthenticatedSubjectCodeRouteImport.update({
    id: '/subject/$code',
    path: '/subject/$code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/battle': typeof AuthenticatedBattleRouteWithChildren
  '/blitz': typeof AuthenticatedBlitzRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/story': typeof AuthenticatedStoryRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/battle/$code': typeof AuthenticatedBattleCodeRoute
  '/learn/$code': typeof AuthenticatedLearnCodeRoute
  '/subject/$code': typeof AuthenticatedSubjectCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/battle': typeof AuthenticatedBattleRouteWithChildren
  '/blitz': typeof AuthenticatedBlitzRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/story': typeof AuthenticatedStoryRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/battle/$code': typeof AuthenticatedBattleCodeRoute
  '/learn/$code': typeof AuthenticatedLearnCodeRoute
  '/subject/$code': typeof AuthenticatedSubjectCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRouteWithChildren
  '/_authenticated/blitz': typeof AuthenticatedBlitzRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/mistakes': typeof AuthenticatedMistakesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/story': typeof AuthenticatedStoryRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/battle/$code': typeof AuthenticatedBattleCodeRoute
  '/_authenticated/learn/$code': typeof AuthenticatedLearnCodeRoute
  '/_authenticated/subject/$code': typeof AuthenticatedSubjectCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/battle'
    | '/blitz'
    | '/dashboard'
    | '/flashcards'
    | '/leaderboard'
    | '/match'
    | '/mistakes'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/shop'
    | '/skills'
    | '/story'
    | '/tutor'
    | '/battle/$code'
    | '/learn/$code'
    | '/subject/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/battle'
    | '/blitz'
    | '/dashboard'
    | '/flashcards'
    | '/leaderboard'
    | '/match'
    | '/mistakes'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/shop'
    | '/skills'
    | '/story'
    | '/tutor'
    | '/battle/$code'
    | '/learn/$code'
    | '/subject/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/battle'
    | '/_authenticated/blitz'
    | '/_authenticated/dashboard'
    | '/_authenticated/flashcards'
    | '/_authenticated/leaderboard'
    | '/_authenticated/match'
    | '/_authenticated/mistakes'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/shop'
    | '/_authenticated/skills'
    | '/_authenticated/story'
    | '/_authenticated/tutor'
    | '/_authenticated/battle/$code'
    | '/_authenticated/learn/$code'
    | '/_authenticated/subject/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blitz': {
      id: '/_authenticated/blitz'
      path: '/blitz'
      fullPath: '/blitz'
      preLoaderRoute: typeof AuthenticatedBlitzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mistakes': {
      id: '/_authenticated/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AuthenticatedMistakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story': {
      id: '/_authenticated/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AuthenticatedStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/$code': {
      id: '/_authenticated/battle/$code'
      path: '/$code'
      fullPath: '/battle/$code'
      preLoaderRoute: typeof AuthenticatedBattleCodeRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/learn/$code': {
      id: '/_authenticated/learn/$code'
      path: '/learn/$code'
      fullPath: '/learn/$code'
      preLoaderRoute: typeof AuthenticatedLearnCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject/$code': {
      id: '/_authenticated/subject/$code'
      path: '/subject/$code'
      fullPath: '/subject/$code'
      preLoaderRoute: typeof AuthenticatedSubjectCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBattleRouteChildren {
  AuthenticatedBattleCodeRoute: typeof AuthenticatedBattleCodeRoute
}

const AuthenticatedBattleRouteChildren: AuthenticatedBattleRouteChildren = {
  AuthenticatedBattleCodeRoute: AuthenticatedBattleCodeRoute,
}

const AuthenticatedBattleRouteWithChildren =
  AuthenticatedBattleRoute._addFileChildren(AuthenticatedBattleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRouteWithChildren
  AuthenticatedBlitzRoute: typeof AuthenticatedBlitzRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedMistakesRoute: typeof AuthenticatedMistakesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedStoryRoute: typeof AuthenticatedStoryRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedLearnCodeRoute: typeof AuthenticatedLearnCodeRoute
  AuthenticatedSubjectCodeRoute: typeof AuthenticatedSubjectCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedBattleRoute: AuthenticatedBattleRouteWithChildren,
  AuthenticatedBlitzRoute: AuthenticatedBlitzRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedMistakesRoute: AuthenticatedMistakesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedStoryRoute: AuthenticatedStoryRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedLearnCodeRoute: AuthenticatedLearnCodeRoute,
  AuthenticatedSubjectCodeRoute: AuthenticatedSubjectCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
