-- Seed grade- and curriculum-specific topics for Matric (9-10), IGCSE (8-10) and FSc (11-12).
-- Each INSERT uses a subquery to look up the subject UUID by its code, so the seed is
-- portable across projects with different auto-generated UUIDs.
-- ON CONFLICT DO NOTHING makes the migration re-runnable safely.

-- ─────────────────────────────────────────────────────────────────────
-- MATRIC GRADE 9
-- ─────────────────────────────────────────────────────────────────────
-- Math
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Matrices and Determinants', 'Matrix notation, operations and determinants', '9', 'matric', 'medium', 1, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Real and Complex Numbers', 'Properties of real numbers and introduction to complex numbers', '9', 'matric', 'easy', 2, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Logarithms', 'Laws of logarithms and common/natural logs', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Algebraic Expressions and Formulas', 'Algebraic identities and manipulation', '9', 'matric', 'easy', 4, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Factorization', 'Factoring polynomials using various techniques', '9', 'matric', 'medium', 5, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Algebraic Manipulation', 'HCF, LCM of algebraic expressions', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Linear Equations and Inequalities', 'Solving equations and inequalities in one variable', '9', 'matric', 'easy', 7, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Linear Graphs and Applications', 'Slope, intercepts and real-world linear models', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Introduction to Coordinate Geometry', 'Distance formula, midpoint and collinearity', '9', 'matric', 'medium', 9, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Congruent Triangles', 'Congruence postulates and proofs', '9', 'matric', 'medium', 10, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Parallelograms and Triangles', 'Properties and theorems of parallelograms', '9', 'matric', 'medium', 11, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Practical Geometry', 'Constructions of triangles and quadrilaterals', '9', 'matric', 'easy', 12, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Statistics and Probability', 'Data collection, frequency tables, mean/median/mode and basic probability', '9', 'matric', 'medium', 13, true from public.subjects s where s.code = 'math' on conflict do nothing;

-- Physics
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Physical Quantities and Measurement', 'SI units, measuring instruments, significant figures', '9', 'matric', 'easy', 1, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Kinematics', 'Speed, velocity, acceleration, equations of motion and graphs', '9', 'matric', 'medium', 2, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Dynamics', 'Newton''s laws, friction, momentum', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Turning Effect of Forces', 'Moments, centre of gravity, equilibrium conditions', '9', 'matric', 'medium', 4, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Gravitation', 'Universal gravitation, gravitational field and satellite motion', '9', 'matric', 'medium', 5, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Work and Energy', 'Work, kinetic/potential energy, conservation of energy, power', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Properties of Matter', 'Density, pressure in liquids, Archimedes'' principle, elasticity', '9', 'matric', 'medium', 7, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Thermal Properties of Matter', 'Temperature, specific heat, latent heat, thermal expansion', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Transfer of Heat', 'Conduction, convection and radiation', '9', 'matric', 'easy', 9, true from public.subjects s where s.code = 'physics' on conflict do nothing;

-- Chemistry
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Fundamentals of Chemistry', 'Branches of chemistry, matter, mixtures and separation', '9', 'matric', 'easy', 1, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Structure of Atoms', 'Sub-atomic particles, electronic configuration, isotopes', '9', 'matric', 'medium', 2, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Periodic Table and Periodicity', 'Periods, groups, periodic trends', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Structure of Molecules', 'Ionic, covalent and coordinate bonding', '9', 'matric', 'medium', 4, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Physical States of Matter', 'Kinetic molecular theory, gas laws, liquids and solids', '9', 'matric', 'medium', 5, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Solutions', 'Types of solutions, concentration, solubility', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electrochemistry', 'Oxidation/reduction, electrolysis, electrochemical cells', '9', 'matric', 'hard', 7, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Chemical Reactivity', 'Activity series, types of chemical reactions', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;

-- Biology
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Introduction to Biology', 'Levels of organisation, branches and careers in biology', '9', 'matric', 'easy', 1, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Solving a Biological Problem', 'Scientific method, hypothesis, data and interpretation', '9', 'matric', 'easy', 2, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Biodiversity', 'Classification system, kingdoms, binomial nomenclature', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Cells and Tissues', 'Cell theory, prokaryotic/eukaryotic, cell organelles, tissues', '9', 'matric', 'medium', 4, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Cell Cycle', 'Mitosis, meiosis and their significance', '9', 'matric', 'hard', 5, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Enzymes', 'Enzyme structure, mechanism and factors affecting activity', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Bioenergetics', 'Photosynthesis and respiration overview', '9', 'matric', 'hard', 7, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Nutrition', 'Autotrophic and heterotrophic nutrition, human digestive system', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Transport', 'Diffusion, osmosis, transport in plants and blood circulation', '9', 'matric', 'hard', 9, true from public.subjects s where s.code = 'biology' on conflict do nothing;

-- Computer Science
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Computer and Its Components', 'Hardware components, CPU, memory and I/O devices', '9', 'matric', 'easy', 1, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'History and Classification of Computers', 'Generations and types of computers', '9', 'matric', 'easy', 2, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Applications of ICT', 'ICT in education, business, healthcare and communication', '9', 'matric', 'easy', 3, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Windows Operating System', 'Desktop, file management, settings and shortcuts', '9', 'matric', 'easy', 4, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Microsoft Word', 'Document creation, formatting and editing', '9', 'matric', 'easy', 5, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Microsoft Excel', 'Spreadsheets, formulas and charts', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Microsoft PowerPoint', 'Presentation design and slide management', '9', 'matric', 'easy', 7, true from public.subjects s where s.code = 'computer' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Microsoft Access', 'Database tables, queries and forms', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'computer' on conflict do nothing;

-- Islamiyat
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Seerat-un-Nabi (Part 1)', 'Life of Prophet Muhammad ﷺ — birth to Hijrah', '9', 'matric', 'medium', 1, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Quran with Translation (Part 1)', 'Selected Surahs with Urdu and English translation', '9', 'matric', 'medium', 2, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Ahadith Mubarkah (Part 1)', 'Selected Hadith on worship and character', '9', 'matric', 'easy', 3, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Tawheed and Risalat', 'Oneness of Allah and prophethood', '9', 'matric', 'easy', 4, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Akhrat and Islamic Beliefs', 'Life after death, Day of Judgement, paradise and hell', '9', 'matric', 'easy', 5, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Khulafa-e-Rashideen', 'The four rightly-guided caliphs and their contributions', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'islamiyat' on conflict do nothing;

-- Urdu
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'نظم — Poetry (Nazm)', 'Selected poems from the textbook with explanation', '9', 'matric', 'medium', 1, true from public.subjects s where s.code = 'urdu' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'نثر — Prose (Nasr)', 'Selected prose chapters from the textbook', '9', 'matric', 'medium', 2, true from public.subjects s where s.code = 'urdu' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'افسانہ — Short Story', 'Short stories and character analysis', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'urdu' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'قواعد — Grammar', 'Urdu grammar rules, sentence structure and parts of speech', '9', 'matric', 'medium', 4, true from public.subjects s where s.code = 'urdu' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'خطوط و مضامین — Letters and Essays', 'Formal and informal writing in Urdu', '9', 'matric', 'medium', 5, true from public.subjects s where s.code = 'urdu' on conflict do nothing;

-- Pakistan Studies / Social
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Pakistan: Physical Features', 'Mountains, rivers, plateaus and plains of Pakistan', '9', 'matric', 'easy', 1, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Climate and Vegetation', 'Seasons, rainfall patterns and natural vegetation', '9', 'matric', 'easy', 2, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Population and Human Resources', 'Demographics, population growth and human development', '9', 'matric', 'medium', 3, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Natural Resources', 'Minerals, forests, water and energy resources', '9', 'matric', 'easy', 4, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Agriculture', 'Crops, irrigation systems and agricultural challenges', '9', 'matric', 'medium', 5, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Industry and Trade', 'Major industries, exports and imports', '9', 'matric', 'medium', 6, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Transport and Communication', 'Road, rail, air and sea transport plus media', '9', 'matric', 'easy', 7, true from public.subjects s where s.code = 'social' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Pakistan''s Foreign Policy', 'Relations with neighbouring and major world powers', '9', 'matric', 'medium', 8, true from public.subjects s where s.code = 'social' on conflict do nothing;

-- ─────────────────────────────────────────────────────────────────────
-- MATRIC GRADE 10
-- ─────────────────────────────────────────────────────────────────────
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Quadratic Equations', 'Solving by factoring, completing the square and quadratic formula', '10', 'matric', 'medium', 1, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Theory of Quadratic Equations', 'Nature of roots, sum/product of roots, formation of equations', '10', 'matric', 'hard', 2, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Variations', 'Direct, inverse and joint variation with applications', '10', 'matric', 'medium', 3, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Partial Fractions', 'Resolving rational expressions into partial fractions', '10', 'matric', 'hard', 4, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Sets and Functions', 'Set operations, types of functions and function composition', '10', 'matric', 'medium', 5, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Basic Statistics', 'Measures of central tendency, dispersion and frequency distribution', '10', 'matric', 'medium', 6, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Introduction to Trigonometry', 'Trigonometric ratios, identities and solving right triangles', '10', 'matric', 'medium', 7, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Chords of a Circle', 'Theorems on chords, arcs and angles', '10', 'matric', 'medium', 8, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Tangent to a Circle', 'Tangent properties and related theorems', '10', 'matric', 'medium', 9, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Practical Geometry (Grade 10)', 'Advanced constructions using compass and ruler', '10', 'matric', 'easy', 10, true from public.subjects s where s.code = 'math' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Simple Harmonic Motion and Waves', 'SHM, wave parameters, transverse and longitudinal waves', '10', 'matric', 'hard', 1, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Sound', 'Sound production, speed of sound, echoes, ultrasound', '10', 'matric', 'medium', 2, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Geometrical Optics', 'Reflection, refraction, lenses and mirrors', '10', 'matric', 'medium', 3, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electrostatics', 'Coulomb''s law, electric field, potential and capacitance', '10', 'matric', 'hard', 4, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Current Electricity', 'Ohm''s law, circuits, resistors, power and energy', '10', 'matric', 'medium', 5, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electromagnetism', 'Magnetic effect of current, electromagnetic induction', '10', 'matric', 'hard', 6, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Basic Electronics', 'Semiconductors, diodes, transistors and logic gates', '10', 'matric', 'hard', 7, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Atomic and Nuclear Physics', 'Atomic models, radioactivity, nuclear reactions and safety', '10', 'matric', 'hard', 8, true from public.subjects s where s.code = 'physics' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Chemical Equilibrium', 'Le Chatelier''s principle, equilibrium constant Kc and Kp', '10', 'matric', 'hard', 1, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Acids, Bases and Salts', 'pH, neutralisation, buffer solutions and salt hydrolysis', '10', 'matric', 'medium', 2, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Organic Chemistry — Introduction', 'Organic compounds, functional groups, IUPAC naming', '10', 'matric', 'medium', 3, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Hydrocarbons', 'Alkanes, alkenes, alkynes and their reactions', '10', 'matric', 'hard', 4, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Biochemistry', 'Carbohydrates, lipids, proteins and nucleic acids', '10', 'matric', 'medium', 5, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'The Atmosphere', 'Composition of air, air pollution and global warming', '10', 'matric', 'easy', 6, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Water', 'Hard water, soft water, water treatment and pollution', '10', 'matric', 'medium', 7, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Gaseous Exchange', 'Gas exchange in plants and humans, breathing mechanism', '10', 'matric', 'medium', 1, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Homeostasis', 'Osmoregulation, thermoregulation and the role of kidneys', '10', 'matric', 'hard', 2, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Coordination and Control', 'Nervous system, brain, sense organs and endocrine system', '10', 'matric', 'hard', 3, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Support and Movement', 'Skeleton, joints, muscles and locomotion', '10', 'matric', 'medium', 4, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Reproduction', 'Asexual and sexual reproduction, human reproductive system', '10', 'matric', 'medium', 5, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Inheritance', 'Mendelian genetics, monohybrid and dihybrid crosses', '10', 'matric', 'hard', 6, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Man and His Environment', 'Ecosystems, food chains, biodiversity and conservation', '10', 'matric', 'medium', 7, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Biotechnology', 'DNA technology, cloning, GM organisms and applications', '10', 'matric', 'hard', 8, true from public.subjects s where s.code = 'biology' on conflict do nothing;

-- ─────────────────────────────────────────────────────────────────────
-- IGCSE GRADE 10 (representative sample — full set mirrors syllabus.ts)
-- ─────────────────────────────────────────────────────────────────────
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Number — Advanced', 'Standard form, bounds, rational/irrational, reciprocals', '10', 'igcse', 'medium', 1, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Algebra — Quadratics', 'Factorising, completing the square, quadratic formula', '10', 'igcse', 'hard', 2, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Simultaneous Equations', 'Linear and non-linear simultaneous equations', '10', 'igcse', 'hard', 3, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Functions', 'Function notation, domain, range, composite and inverse', '10', 'igcse', 'hard', 4, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Geometry — Circle Theorems', 'All circle theorems and proofs', '10', 'igcse', 'hard', 5, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Trigonometry — Sine and Cosine Rules', 'Non-right triangles, sine rule, cosine rule, area formula', '10', 'igcse', 'hard', 6, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Vectors', 'Vector notation, addition, subtraction and column vectors', '10', 'igcse', 'hard', 7, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Statistics — Advanced', 'Histograms, box plots, standard deviation, scatter graphs', '10', 'igcse', 'hard', 8, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Probability — Advanced', 'Conditional probability, Venn diagrams, tree diagrams', '10', 'igcse', 'hard', 9, true from public.subjects s where s.code = 'math' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Kinematics', 'SUVAT equations, displacement-time and velocity-time graphs', '10', 'igcse', 'medium', 1, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Forces and Newton''s Laws', 'Free body diagrams, tension, friction, resultant force', '10', 'igcse', 'medium', 2, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Momentum and Impulse', 'Conservation of momentum, elastic and inelastic collisions', '10', 'igcse', 'hard', 3, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Thermal Physics', 'Gas laws, internal energy, specific heat, latent heat', '10', 'igcse', 'hard', 4, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Waves and Electromagnetic Spectrum', 'Wave properties, EM spectrum, diffraction and interference', '10', 'igcse', 'hard', 5, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electricity and Circuits', 'Ohm''s law, resistivity, series/parallel, power', '10', 'igcse', 'medium', 6, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electromagnetism', 'Magnetic fields, electromagnetic induction, motors', '10', 'igcse', 'hard', 7, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Nuclear Physics', 'Radioactivity, types of radiation, half-life, nuclear equations', '10', 'igcse', 'hard', 8, true from public.subjects s where s.code = 'physics' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Atomic Structure and Bonding', 'Electron config, ionic/covalent/metallic bonding', '10', 'igcse', 'hard', 1, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Stoichiometry', 'Mole calculations, limiting reagents, percentage yield', '10', 'igcse', 'hard', 2, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electrochemistry', 'Electrolysis, electrode products, electroplating', '10', 'igcse', 'hard', 3, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Energetics', 'Enthalpy changes, Hess''s law, bond energies', '10', 'igcse', 'hard', 4, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Reaction Kinetics', 'Collision theory, activation energy, catalysts', '10', 'igcse', 'medium', 5, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Acids, Bases and Salts', 'Strong/weak acids, buffer solutions, pH calculations', '10', 'igcse', 'hard', 6, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Organic Chemistry', 'Hydrocarbons, functional groups, reactions and mechanisms', '10', 'igcse', 'hard', 7, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Periodic Table and Elements', 'Group properties, transition metals, extraction of metals', '10', 'igcse', 'medium', 8, true from public.subjects s where s.code = 'chemistry' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Cell Structure and Division', 'Organelles, mitosis, meiosis and stem cells', '10', 'igcse', 'medium', 1, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Biological Molecules and Enzymes', 'Macromolecules, enzyme kinetics and inhibition', '10', 'igcse', 'hard', 2, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Plant Nutrition and Gas Exchange', 'Photosynthesis, leaf structure, transpiration', '10', 'igcse', 'medium', 3, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Transport in Humans', 'Heart, blood vessels, blood composition and immune system', '10', 'igcse', 'hard', 4, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Excretion and Homeostasis', 'Kidney function, osmoregulation, thermoregulation', '10', 'igcse', 'hard', 5, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Coordination and Response', 'Nervous system, hormones, sense organs, reflex arcs', '10', 'igcse', 'hard', 6, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Inheritance and Genetics', 'DNA, genes, monohybrid cross, sex-linkage, mutations', '10', 'igcse', 'hard', 7, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Natural Selection and Evolution', 'Darwin''s theory, adaptation, speciation', '10', 'igcse', 'medium', 8, true from public.subjects s where s.code = 'biology' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Organisms and the Environment', 'Ecosystems, food chains, carbon cycle, biodiversity', '10', 'igcse', 'medium', 9, true from public.subjects s where s.code = 'biology' on conflict do nothing;

-- ─────────────────────────────────────────────────────────────────────
-- FSc GRADE 11 (key subjects)
-- ─────────────────────────────────────────────────────────────────────
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Number System', 'Real, complex numbers and their properties', '11', 'fsc', 'medium', 1, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Sets, Functions and Groups', 'Set operations, relations, types of functions and groups', '11', 'fsc', 'hard', 2, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Matrices and Determinants', 'Operations, inverse, Cramer''s rule, system of equations', '11', 'fsc', 'hard', 3, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Quadratic Equations (FSc)', 'Roots, discriminant, nature of roots and symmetric functions', '11', 'fsc', 'medium', 4, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Sequences and Series', 'AP, GP, HP, sum to n terms and infinite series', '11', 'fsc', 'hard', 5, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Permutation, Combination and Probability', 'Counting methods and classical probability', '11', 'fsc', 'hard', 6, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Mathematical Induction and Binomial Theorem', 'Proofs by induction and binomial expansion', '11', 'fsc', 'hard', 7, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Fundamentals of Trigonometry', 'Angle measurement, circular functions and identities', '11', 'fsc', 'medium', 8, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Trigonometric Identities', 'Compound, double-angle and half-angle formulae', '11', 'fsc', 'hard', 9, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Trigonometric Functions and Graphs', 'Graphs of sin, cos, tan and their transformations', '11', 'fsc', 'hard', 10, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Application of Trigonometry', 'Sine rule, cosine rule and area of triangle', '11', 'fsc', 'hard', 11, true from public.subjects s where s.code = 'math' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Measurements', 'Physical quantities, SI units, errors, significant figures', '11', 'fsc', 'easy', 1, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Vectors and Equilibrium', 'Vector operations, resolution, torque and equilibrium', '11', 'fsc', 'hard', 2, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Motion and Force', 'Kinematics, Newton''s laws, friction, projectile motion', '11', 'fsc', 'hard', 3, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Work and Energy (FSc)', 'Work, KE, PE, conservative forces, power and efficiency', '11', 'fsc', 'medium', 4, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Circular Motion', 'Angular velocity, centripetal acceleration and gravitation', '11', 'fsc', 'hard', 5, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Oscillations', 'SHM, energy in SHM, pendulum and resonance', '11', 'fsc', 'hard', 6, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Waves (FSc)', 'Wave properties, superposition, standing waves', '11', 'fsc', 'hard', 7, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Physical Optics', 'Interference, diffraction and polarisation', '11', 'fsc', 'very_hard', 8, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Heat and Thermodynamics', 'Internal energy, first law, Carnot engine, entropy', '11', 'fsc', 'very_hard', 9, true from public.subjects s where s.code = 'physics' on conflict do nothing;

-- ─────────────────────────────────────────────────────────────────────
-- FSc GRADE 12 (key subjects)
-- ─────────────────────────────────────────────────────────────────────
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Functions and Limits', 'Limits, continuity, L''Hôpital''s rule and algebraic functions', '12', 'fsc', 'hard', 1, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Differentiation', 'Rules of differentiation, chain rule, implicit differentiation', '12', 'fsc', 'hard', 2, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Higher Order Derivatives and Applications', 'Maxima/minima, curve sketching, related rates', '12', 'fsc', 'very_hard', 3, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Integration', 'Indefinite integrals, standard forms and techniques', '12', 'fsc', 'hard', 4, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Definite Integration and Applications', 'Area under curve, volume of revolution', '12', 'fsc', 'very_hard', 5, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Linear Inequalities and Linear Programming', 'Feasible region, objective function and optimisation', '12', 'fsc', 'medium', 6, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Conic Sections', 'Circle, parabola, ellipse and hyperbola — equations and graphs', '12', 'fsc', 'very_hard', 7, true from public.subjects s where s.code = 'math' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Vectors (FSc)', '3D vectors, dot product, cross product and applications', '12', 'fsc', 'very_hard', 8, true from public.subjects s where s.code = 'math' on conflict do nothing;

insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electrostatics', 'Coulomb''s law, electric field, flux, Gauss''s law, potential', '12', 'fsc', 'very_hard', 1, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Current Electricity (FSc)', 'Kirchhoff''s laws, Wheatstone bridge, potentiometer', '12', 'fsc', 'hard', 2, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electromagnetism (FSc)', 'Ampere''s law, solenoid, magnetic force, Hall effect', '12', 'fsc', 'very_hard', 3, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electromagnetic Induction', 'Faraday''s law, Lenz''s law, self and mutual inductance', '12', 'fsc', 'very_hard', 4, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Alternating Current', 'RMS values, transformers, resonance and AC circuits', '12', 'fsc', 'very_hard', 5, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Electronics', 'Diodes, transistors, op-amps and digital logic', '12', 'fsc', 'very_hard', 6, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Dawn of Modern Physics', 'Photoelectric effect, Compton scattering, de Broglie waves', '12', 'fsc', 'very_hard', 7, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Atomic Spectra', 'Bohr model, hydrogen spectrum, X-rays and lasers', '12', 'fsc', 'very_hard', 8, true from public.subjects s where s.code = 'physics' on conflict do nothing;
insert into public.topics (subject_id, name, description, grade, curriculum, difficulty, sort_order, is_active) select s.id, 'Nuclear Physics', 'Nuclear forces, radioactivity, fission, fusion and reactors', '12', 'fsc', 'very_hard', 9, true from public.subjects s where s.code = 'physics' on conflict do nothing;
